add and fix about HSR function.
SIGVerse/sigverse_unity_project pull request #1
Opened 2018-11-12 07:17 UTC by Noriyuki-Kugou

・Support of multipoint joint_trajectry.
・/hsrb/omni_base_controller/command interface was added.
・The gripper interface was adjusted to the real HSR interface.

2018-11-12 08:43 UTC, hiroki-yamada commented
Please make method names easier to understand.

2018-11-12 09:00 UTC, hiroki-yamada commented
Please use handLDistal instead of handLMimicDistal.

2018-11-13 07:33 UTC, hiroki-yamada requested changes

2018-11-13 07:33 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectoryOmni.cs
> +		private bool CheckTrajectryMsg(ref SIGVerse.RosBridge.trajectory_msgs.JointTrajectory msg)
Please rename  the method

2018-11-13 07:36 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectory.cs
> +			if(msg.joint_names.Count != msg.points[0].positions.Count) { return false; }
Please check all points.

2018-11-13 07:39 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectory.cs
> +					}
Please delete the trailing space.

2018-11-13 07:40 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectory.cs
> +			else if (msg.joint_names.Count == 1)//Head
Head -> Hand

2018-11-13 07:57 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectory.cs
> +				if (0 <= msg.joint_names.IndexOf(HSRCommon.HeadPanJointName) && 0 <= msg.joint_names.IndexOf(HSRCommon.HeadTiltJointName))
Please use Contains instead of IndexOf for readability.

2018-11-13 08:07 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectory.cs
> +					this.trajectoryInfoMap[name] = new TrajectoryInfo(Time.time, durations, positions, Time.time, HSRCommon.GetCorrectedJointsEulerAngle(this.handLProximalLink.localEulerAngles.x, name) * Mathf.Deg2
handLProximalLink??

2018-11-13 08:26 UTC, hiroki-yamada commented on SIGVerseProject/Assets/SIGVerse/Models/Robot/HSR/Scripts/HSRSubJointTrajectory.cs
> +			if (this.IsOverLimitSpeed() == true) { return; }
In the case of joints other than omni, please do not stop even if it over the limit speed.

2018-11-16 12:55 UTC, Noriyuki-Kugou commented
I rewrote some code according your comment. so please check the code.

2018-12-26 10:22 UTC, hiroki-yamada approved these changes

2018-12-26 10:57 UTC, merged